


export const metadata = {
  title: ' this is chat application',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   
   

        {children}
      
    </html>
  )
}
