


import './globals.css'
import Foter from './head/Footer'
import Navbar from './head/Nav'

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import 'bootstrap/dist/css/bootstrap.min.css';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
   <Navbar/>
   <ToastContainer 
   position="top-center"/>
   {/* <Auth0Provider
    domain="dev-f8kxln124dmyxxsu.us.auth0.com"
    clientId="OJneKjbyhUWsYBep764SCvFZv73duhF8"
    authorizationParams={{
      redirect_uri: window.location.origin
    }}
  > */}
        {children}

        {/* </Auth0Provider> */}
        <Foter/>
        </body>
    </html>
  )
}


// import React from 'react';
// import { createRoot } from 'react-dom/client';

// import App from './App';

// const root = createRoot(document.getElementById('root'));

// root.render(
// <Auth0Provider
//     domain="dev-f8kxln124dmyxxsu.us.auth0.com"
//     clientId="OJneKjbyhUWsYBep764SCvFZv73duhF8"
//     authorizationParams={{
//       redirect_uri: window.location.origin
//     }}
//   >
//     <App />
//   </Auth0Provider>,
// );